# Generated by Django 5.0.4 on 2024-04-11 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_articlecomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecomment',
            old_name='post',
            new_name='article',
        ),
    ]
